name: findie
description: A smart Lost & Found platform for campus or local community use.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  web: any
  # Supabase dependencies
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  permission_handler: ^11.2.0
  # State management
  flutter_riverpod: ^2.4.9
  # OCR and image processing
  google_ml_kit: ^0.16.3
  # Real-time messaging
  stream_chat_flutter: ^7.2.0
  # Animations
  lottie: ^2.7.0
  # Date formatting
  intl: ^0.19.0
  # UUID generation
  uuid: ^4.3.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/animations/